version: "3.8"

services:
  server:
    container_name: server
    build:
      context: ..
      dockerfile: docker/server/Dockerfile
    ports:
      - "9000:9000"

  client:
    container_name: client
    build:
      context: ..
      dockerfile: docker/client/Dockerfile
    depends_on:
      - server
